"""Generate the Mac app's prompts from app.py so the native app and the server never drift.

Writes mac/Sources/FlowCore/GeneratedPrompts.swift and mac/Tests/FlowCoreTests/PromptFixtures.swift.
Run:  python scripts/export_mac_prompts.py          (rewrite the files)
      python scripts/export_mac_prompts.py --check  (exit 1 if they are out of date; tests run this)
"""
import importlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
flow = importlib.import_module("app")

HEADER = "// Generated by scripts/export_mac_prompts.py from app.py. Do not edit by hand.\n"
SOURCE = ROOT / "mac/Sources/FlowCore/GeneratedPrompts.swift"
FIXTURES = ROOT / "mac/Tests/FlowCoreTests/PromptFixtures.swift"


def lit(s: str) -> str:
    """A Swift string literal. JSON escaping is valid Swift except for \\uXXXX, so spell those as \\u{XXXX}."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\u{%x}" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def snippet_header() -> str:
    rules = flow.snippet_rules(["X"])
    return rules[: rules.index('  1. "X"')]


def source() -> str:
    styles = ",\n".join(f"        {lit(s)}: {lit(flow.system_prompt(s))}" for s in flow.STYLE_FORMATS)
    return (HEADER + "enum GeneratedPrompts {\n"
            f"    static let system: [String: String] = [\n{styles},\n    ]\n"
            f"    static let commandTemplate = {lit(flow.command_prompt('{{INSTRUCTION}}'))}\n"
            f"    static let snippetHeader = {lit(snippet_header())}\n"
            f"    static let defaultModel = {lit(flow.LLM_MODEL)}\n"
            f"    static let fastHints: [String] = [{', '.join(lit(h) for h in flow.FAST_HINTS)}]\n"
            f"    static let maxModelTries = {flow.MAX_MODEL_TRIES}\n"
            "}\n")


def fixtures() -> str:
    cues = ["my calendly link", "  my address  ", "", "x" * 100]
    instruction = "  make it shorter  "
    base = flow.system_prompt("message")
    with_snips = base.replace("\nReturn only", flow.snippet_rules(cues) + "\nReturn only", 1)
    return (HEADER + "enum PromptFixtures {\n"
            f"    static let snippetCues: [String] = [{', '.join(lit(c) for c in cues)}]\n"
            f"    static let messageWithSnippets = {lit(with_snips)}\n"
            f"    static let instruction = {lit(instruction)}\n"
            f"    static let command = {lit(flow.command_prompt(instruction))}\n"
            f"    static let auto = {lit(flow.system_prompt('auto'))}\n"
            "}\n")


def main() -> int:
    wanted = {SOURCE: source(), FIXTURES: fixtures()}
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, text in wanted.items() if not p.exists() or p.read_text() != text]
        if stale:
            print("Out of date, run python scripts/export_mac_prompts.py:", ", ".join(stale))
            return 1
        return 0
    for path, text in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(json.dumps([str(p.relative_to(ROOT)) for p in wanted]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
